title: Captivi
description: Seamless Guest WiFi Access for UniFi & Square POS
url: "http://sysadmininator.com/captivi-website/"  # Set this to your site URL or GitHub Pages URL
baseurl: "captivi-website"  # Leave blank for root deployment
