title: Captivi
description: Seamless Guest WiFi Access for UniFi & Square POS
url: "https://captivi.info"  # Set this to your site URL or GitHub Pages URL
baseurl: ""  # Leave blank for root deployment
